todoProject/todo/urls.py
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "todo"

urlpatterns = [
    path('', views.index, name="index"),
    path('add/',views.add,name="add"),
    path('<task_id>',views.task,name="task"),
    path('delete_task/<task_id>',views.delete_task,name="delete_task")
]

todoProject/todoProject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "main"

urlpatterns = [
    path('',views.index,name="index"),
    path('admin/', admin.site.urls),
    path('todo/',include("todo.urls"),name="todo")
]

todoProject/todo/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    task = models.CharField(max_length=64)

    def __str__(self):
        return self.task

todoProject/todo/forms.py
from django import forms

class AddTaskForm(forms.Form):
    task = forms.CharField(label="Task")

todoProject/todo/views.py
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render,redirect
from .forms import AddTaskForm
from .models import Task

def index(request):
    context = {"tasks":Task.objects.all()}
    return render(request,"todo/index.html",context)

def add(request):
    # if request.method == "POST":
    #     form = AddTaskForm(request.POST)
    #     if form.is_valid():
    #         task = form.cleaned_data["task"]
    #         new_task = Task(task=task)
    #         new_task.save()
    #         return HttpResponseRedirect(reverse("todo:index"))
    #     else:
    #         return render(request,'todo/add.html',{"form":form})
    # else:
    #     form = AddTaskForm()
    #     context = {"form":form}
    #     return render(request,'todo/add.html',context)

    form = AddTaskForm(request.POST or None)
    if form.is_valid():
        task = form.cleaned_data["task"]
        new_task = Task(task=task)
        new_task.save()
        return redirect("todo:index")
    context = {"form":form}
    return render(request,'todo/add.html',context)

def task(request, task_id):
    task = Task.objects.get(pk=task_id)
    return render(request, "todo/task.html",{"task":task})

def delete_task(request,task_id):
    task = Task.objects.get(pk=task_id)
    task.delete()
    return redirect('todo:index')

todoProject/todoProject/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"todoProject/index.html")

todoProject/todo/templates/todo/add.html
{% extends 'todo/layout.html' %}

{% block content %}
<h1>Add Tasks</h1>
<form action="{% url 'todo:add' %}" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" name="submit" id="">
</form>

<a href=" {% url 'todo:index' %} ">View Tasks</a>
{% endblock content %}

todoProject/todo/templates/todo/index.html
{% extends 'todo/layout.html' %}

{% block content %}
<h1>Tasks</h1>
<ul>
    {% for task in tasks %}
        <li> <a href="{% url 'todo:task' task.id%}">{{task}}</a> - Edit <a href="{% url 'todo:delete_task' task.id %}">Delete</a></li>
    {% endfor %}
</ul>
<a href=" {% url 'todo:add' %} ">Add task</a>
{% endblock content %}

todoProject/todo/templates/todo/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do App</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

todoProject/todo/templates/todo/task.html
{% extends 'todo/layout.html' %}

{% block content %}
    <h1> {{task.id}} - {{task.task}} </h1>
    <a href="{% url 'todo:index' %}">Back to all the Tasks</a>
{% endblock content %}

todoProject/todo/templates/todoProject/index.html
This is the Homepage